// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2_Zg9EBRkZ_Ni1yLWvU7vfXKeHPL7K4',
    appId: '1:1018573916466:web:5bb71583ce3a3b7c7d6f2b',
    messagingSenderId: '1018573916466',
    projectId: 'hotelhub-45953',
    authDomain: 'hotelhub-45953.firebaseapp.com',
    storageBucket: 'hotelhub-45953.appspot.com',
    measurementId: 'G-0F124MEQEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCACWyGuxY-Fp3yytnchYqVNk3UwvuPZ9I',
    appId: '1:1018573916466:android:b863b437802b79c57d6f2b',
    messagingSenderId: '1018573916466',
    projectId: 'hotelhub-45953',
    storageBucket: 'hotelhub-45953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARi5SgEvd2Qkpik1HwtfKJARaYWAK5cCw',
    appId: '1:1018573916466:ios:a0d3981dbe5adda17d6f2b',
    messagingSenderId: '1018573916466',
    projectId: 'hotelhub-45953',
    storageBucket: 'hotelhub-45953.appspot.com',
    iosBundleId: 'com.example.oyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARi5SgEvd2Qkpik1HwtfKJARaYWAK5cCw',
    appId: '1:1018573916466:ios:a0d3981dbe5adda17d6f2b',
    messagingSenderId: '1018573916466',
    projectId: 'hotelhub-45953',
    storageBucket: 'hotelhub-45953.appspot.com',
    iosBundleId: 'com.example.oyo',
  );
}
